# Generated by Django 5.1.1 on 2024-11-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_d', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('original_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('upperwear_img', models.ImageField(upload_to='new_arrival_img')),
            ],
        ),
    ]
