# Generated by Django 5.1.1 on 2024-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartupperwear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upperwear',
            name='category',
            field=models.CharField(choices=[('SHIRTS', 'shirts'), ('T_SHIRTS', 't-shirts'), ('SWEATSHIRTS', 'sweatshirts'), ('TROUSERS', 'trousers'), ('SHORTS', 'shorts'), ('TRENDING', 'trending')], max_length=30),
        ),
    ]
