# Generated by Django 5.1.1 on 2024-11-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartupperwear',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.new_arrival'),
        ),
        migrations.AddField(
            model_name='new_arrival',
            name='category',
            field=models.CharField(choices=[('NEWARRIVAL', 'newarrival'), ('SHIRTS', 'shirts'), ('T_SHIRTS', 't-shirts'), ('SWEATSHIRTS', 'sweatshirts'), ('TROUSERS', 'trousers'), ('SHORTS', 'shorts'), ('TRENDING', 'trending')], default=1000, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_arrival',
            name='original_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='Cartextra',
        ),
        migrations.DeleteModel(
            name='upperwear',
        ),
    ]
