# Generated by Django 5.1.1 on 2025-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartupperwear',
            name='size',
            field=models.CharField(default='S', max_length=50),
        ),
    ]
